apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: hypriot/rpi-mysql
        env:
        - name: MYSQL_USER
          valueFrom:
             secretKeyRef:
                 name: mysql-credentials
                 key: user
        - name: MYSQL_PASSWORD
          valueFrom:
             secretKeyRef:
                 name: mysql-credentials
                 key: password
        - name: MYSQL_DATABASE
          value: demo
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
                 name: mysql-credentials
                 key: rootpw
        - name: MYSQL_HOST
          value: mysql.default.svc.cluster.local
        ports:
        - containerPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
